auth:
  replicaCount: 1
  image:
    repository: docker-registry-server:5000/auth
    tag: develop-init
    pullPolicy: IfNotPresent
  configmap:
    enabled: true
    values:
      SPRING_PROFILES_ACTIVE: dev
      config_host: ml-config-rollout-active-svc.ml-dev # configmap
  ingress:
    enabled: ture
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/affinity: cookie
      nginx.ingress.kubernetes.io/session-cookie-hash: sha1
      nginx.ingress.kubernetes.io/session-cookie-name: CMSESSION
    hosts:
      - host: dev-auth.mallowlink.com
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: auth-rollout-active-svc
                port:
                  name: http
  envFrom:
    - configMapRef:
        name: pay-test-auth-cm
    - secretRef:
        name: config-key-scr

  rollout:
    strategy:
      blueGreen:
        autoPromotionEnabled: true
  secrets:
    enabled: false
  otel:
    exporterEndpoint: "http://monitoring-opentelemetry-collector.logging:4317"


